# Generated by Django 4.2.16 on 2024-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages1', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.UUIDField(unique_for_date='publish'),
        ),
    ]
